/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#define DATE_PROG 0x31234567
#define DATE_VERS 1
#define DATE 1
extern  char ** date_1();
extern int date_prog_1_freeresult ();

#endif /* !_DATE_H_RPCGEN */
