/*
 * date_proc.c - remote procedures; called by server stub.
 */
#include <rpc/rpc.h>	/* standard RPC include file */
#include <time.h>
#include <sys/types.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sys/resource.h>

#include "date.h"	/* this file is generated by rpcgen */

#define MAX_LEN 100
#define MAX_LINE_LEN 256
#define MAX_STR_LEN 100



/*
 * Return the binary date and time.
 */
char ** date_1(long *option)
{
    struct tm *timeptr; /* Pointer to time structure      */
    time_t clock;       /* Clock value (in secs)          */
    static char *ptr;   /* Return string                  */
    static char err[] = "Invalid Response \0";
    static char err2[] = "Error executing command \0";
    static char s[MAX_LEN];

    clock = time(0);
    timeptr = localtime(&clock);

    switch(*option)
        {
        case 1: // Date Only
                strftime(s,MAX_LEN,"%A, %B %d, %Y",timeptr);
                ptr=s;
                break;

        case 2: // Time Only
                strftime(s,MAX_LEN,"%T",timeptr);
                ptr=s;
                break;

        case 3: // Time and Date
                strftime(s,MAX_LEN,"%A, %B %d, %Y - %T",timeptr);
                ptr=s;
                break;

        case 4: {// CPU Usage
                ptr=s;
                break;}

        case 5: {// Memory Usage
                struct rusage r_usage;
                getrusage(RUSAGE_SELF,&r_usage);
                snprintf(s, MAX_LEN, "Memory usage: %ld kilobytes", r_usage.ru_maxrss);
                s[MAX_LEN - 1] = '\0';
                ptr=s;
                break;}

        case 6: {// Process Count
                int process_count = 0;
                FILE *fp;
                char command[50];
                char path[100];

                sprintf(command, "ps -e | wc -l");

                fp = popen(command, "r");
                if (fp == NULL) {
                        ptr=err2;
                        break;
                }

                if (fgets(path, sizeof(path), fp) != NULL) {
                        process_count = atoi(path);
                        process_count--; 
                }

                pclose(fp);

                snprintf(s, MAX_LEN, "Number of processes running: %d", process_count);
                s[MAX_LEN - 1] = '\0';
                ptr=s;
                break;}
        
        case 7: // Load procs per minute
                ptr=s;
                break;

        default: ptr=err;
                 break;
        }
    return(&ptr);
}